PREFIX m4s: <http://purl.org/map4scrutiny-core#>
PREFIX polis-ini: <http://purl.org/polis/ar/initiatives#>
PREFIX polis-core: <http://purl.org/polis/ar/core#>
PREFIX polis-graph: <http://purl.org/polis/ar/graph#>
PREFIX ocd: <http://dati.camera.it/ocd/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX qudt: <http://qudt.org/schema/qudt/>

SELECT ?mp1Name WHERE {
    ?mp a m4s:Parliamentarian ; foaf:name ?mp1Name ;
       ocd:rif_mandatoCamera [ polis-core:hasMembership [ polis-core:isMemberOf polis-graph:JPP ] ]
}
ORDER BY ?mp1Name
