---
config:
  layout: elk
---
flowchart LR
Bodies["Body<br>(org:Organization)"] -- hasIdentifier --> bid["ID<br>(dcterms:identifier)"]
Bodies -- hasName --> bname["Name<br>(schema:name)"]
Bodies -- hasAcronym --> bacr["Acronym<br>(org:alternateName)"]
Bodies -- performedRole --> bcap["Role<br>(rdfs:label)"]
Bodies -- hasMemberStatus --> bmstat["Member Status<br>(skos:Concept)"]
Bodies -- isType --> btype["Body Type<br>(skos:Concept)"]

btype -->|"skos:inScheme"| btypeEnum

subgraph btypeEnum["Body Type Scheme (skos:ConceptScheme)"]
    bt1["Commission"]
    bt2["Subcommission"]
    bt3["Working Group"]
    bt4["AR Working Group"]
end

bmstat -->|"skos:inScheme"| bmstatEnum

subgraph bmstatEnum["Member Status Scheme (skos:ConceptScheme)"]
    ms1["Effective"]
    ms2["Alternate"]
end