---
config:
  layout: elk
---
flowchart LR
    Decoration["Decoration<br>(schema:award)"] -- hasIdentifier --> did["ID<br>(dcterms:identifier)"]
    Decoration -- title --> ddes["Title<br>(rdfs:label)"]
    Decoration -- order --> dorder["Order<br>(schema:position)"]