---
config:
  layout: elk
---
flowchart LR
    Work["Published Work<br>(bibo:Document)"] -- hasIdentifier --> wid["ID<br>(dcterms:identifier)"]
    Work -- title --> wdes["Title<br>(rdfs:label)"]
    Work -- order --> worder["Order<br>(schema:position)"]
