---
config:
  layout: elk
---
flowchart LR
    Title["Title<br>(schema:hasCredential)"] -- hasIdentifier --> tid["ID<br>(dcterms:identifier)"]
    Title -- title --> tdes["Title<br>(rdfs:label)"]
    Title -- order --> torder["Order<br>(schema:position)"]